"""removing the testing column

Revision ID: 07f2f1ba7086
Revises: 3a7ead284f04
Create Date: 2026-09-09 11:55:17.454364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '07f2f1ba7086'
down_revision: Union[str, None] = '3a7ead284f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'completed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('completed_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
