"""add cascade delete to reminder recipient

Revision ID: 0f28ecca21a6
Revises: 3bb032ecbd7d
Create Date: 2026-09-16 12:55:19.236540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f28ecca21a6'
down_revision: Union[str, None] = '3bb032ecbd7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_constraint('reminders_ibfk_2', 'reminders', type_='foreignkey')

    op.create_foreign_key(
        None,
        'reminders',
        'recipients',
        ['recipient_id'],
        ['id'],
        ondelete='CASCADE',
    )

    # Add nullable first so existing users are not a problem
    op.add_column(
        'users',
        sa.Column('notify_on_response', sa.Boolean(), nullable=True),
    )

    op.add_column(
        'users',
        sa.Column('reminder_template', sa.Text(), nullable=True),
    )

    # Set values for existing users
    op.execute(
        sa.text(
            """
            UPDATE users
            SET
                notify_on_response = 1,
                reminder_template = :template
            """
        ).bindparams(
            template=(
                "Hi {name},\n\n"
                "Just following up on my previous email as the response deadline "
                "is approaching. Please let me know if you've had a chance to "
                "review it.\n\n"
                "Best,\n"
                "Fuad"
            )
        )
    )

    # Now make them required
    op.alter_column(
        'users',
        'notify_on_response',
        existing_type=sa.Boolean(),
        nullable=False,
    )

    op.alter_column(
        'users',
        'reminder_template',
        existing_type=sa.Text(),
        nullable=False,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reminder_template')
    op.drop_column('users', 'notify_on_response')
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.create_foreign_key('reminders_ibfk_2', 'reminders', 'recipients', ['recipient_id'], ['id'])
    # ### end Alembic commands ###
