"""adding a column on the reminders table

Revision ID: 3a7ead284f04
Revises: 9401832d5be1
Create Date: 2026-09-09 11:53:59.295768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a7ead284f04'
down_revision: Union[str, None] = '9401832d5be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'completed_at')
    # ### end Alembic commands ###
