"""makin the emails a unique constraint

Revision ID: 3bb032ecbd7d
Revises: 5adf08db876f
Create Date: 2026-09-09 15:51:52.299303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb032ecbd7d'
down_revision: Union[str, None] = '5adf08db876f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recipients_email', table_name='recipients')
    op.create_index(op.f('ix_recipients_email'), 'recipients', ['email'], unique=False)
    op.create_unique_constraint(None, 'recipients', ['user_id', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipients', type_='unique')
    op.drop_index(op.f('ix_recipients_email'), table_name='recipients')
    op.create_index('ix_recipients_email', 'recipients', ['email'], unique=True)
    # ### end Alembic commands ###
