"""update database tables

Revision ID: 45c03ef1d653
Revises: c34b3ce73933
Create Date: 2026-09-09 13:51:05.817648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c03ef1d653'
down_revision: Union[str, None] = 'c34b3ce73933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracked_emails', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tracked_emails', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracked_emails', type_='foreignkey')
    op.drop_column('tracked_emails', 'user_id')
    # ### end Alembic commands ###
