"""add completed_at to tracked_email

Revision ID: 9401832d5be1
Revises: 145a317b44e4
Create Date: 2026-09-08 11:19:33.199011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9401832d5be1'
down_revision: Union[str, None] = '145a317b44e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracked_emails', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracked_emails', 'completed_at')
    # ### end Alembic commands ###
