"""add user relationship to google auth

Revision ID: b10802fc8e8e
Revises: 0f28ecca21a6
Create Date: 2026-09-17 16:21:46.172451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b10802fc8e8e'
down_revision: Union[str, None] = '0f28ecca21a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_auth', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'google_auth', ['user_id'])
    op.create_foreign_key(None, 'google_auth', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'google_auth', type_='foreignkey')
    op.drop_constraint(None, 'google_auth', type_='unique')
    op.drop_column('google_auth', 'user_id')
    # ### end Alembic commands ###
